/**
 * Represents a String based key which consists of two components - a namespace and a key.
 * 
 * Namespaces may only contain lowercase alphanumeric characters, periods, underscores, and hyphens.
 * Keys may only contain lowercase alphanumeric characters, periods, underscores, hyphens, and forward slashes.
 * 
 * @see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/NamespacedKey.html
 */

/** The namespace representing all keys generated by Bukkit for backwards compatibility measures */
export const BUKKIT_NAMESPACE = "bukkit";

/** The namespace representing all inbuilt keys */
export const MINECRAFT_NAMESPACE = "minecraft";


export interface BukkitNamespacedKey {
  /**
   * Gets the key component of this NamespacedKey.
   * @returns The key
   */
  getKey(): string;

  /**
   * Gets the namespace component of this NamespacedKey.
   * @returns The namespace
   */
  getNamespace(): string;

  /**
   * Returns the string representation of this key.
   * @returns String in format "namespace:key"
   */
  toString(): string;
}

/** Reference to the Java NamespacedKey class */
export const NamespacedKeyClass = org.bukkit.NamespacedKey;

/**
 * Create a key in a specific namespace.
 * 
 * @param namespace - The namespace (lowercase alphanumeric, periods, underscores, hyphens)
 * @param key - The key (lowercase alphanumeric, periods, underscores, hyphens, forward slashes)
 * @returns A new NamespacedKey
 * 
 * @example
 * const key = createNamespacedKey("myplugin", "custom_item");
 * // Result: "myplugin:custom_item"
 */
export function createNamespacedKey(namespace: string, key: string): BukkitNamespacedKey {
  return new org.bukkit.NamespacedKey(namespace, key);
}

/**
 * Create a key in the plugin's namespace.
 * 
 * @param plugin - The plugin instance
 * @param key - The key
 * @returns A new NamespacedKey with the plugin's namespace
 * 
 * @example
 * const key = createPluginKey(PaperTS.getJavaPlugin(), "my_key");
 */
export function createPluginKey(plugin: any, key: string): BukkitNamespacedKey {
  return new org.bukkit.NamespacedKey(plugin, key);
}

/**
 * Get a key in the Minecraft namespace.
 * 
 * @param key - The key
 * @returns A new NamespacedKey with "minecraft" namespace
 * 
 * @example
 * const key = minecraftKey("diamond");
 * // Result: "minecraft:diamond"
 */
export function minecraftKey(key: string): BukkitNamespacedKey {
  return org.bukkit.NamespacedKey.minecraft(key);
}

/**
 * Get a NamespacedKey from the supplied string.
 * 
 * @param key - String in format "namespace:key" or just "key" (uses minecraft namespace)
 * @returns The parsed NamespacedKey or null if invalid
 * 
 * @example
 * const key1 = fromString("minecraft:diamond");  // minecraft:diamond
 * const key2 = fromString("diamond");            // minecraft:diamond
 * const key3 = fromString("myplugin:item");      // myplugin:item
 */
export function fromString(key: string): BukkitNamespacedKey | null {
  return org.bukkit.NamespacedKey.fromString(key);
}

/**
 * Get a NamespacedKey from the supplied string with a default namespace.
 * 
 * @param key - String in format "namespace:key" or just "key"
 * @param defaultNamespace - Plugin to use as default namespace if not specified
 * @returns The parsed NamespacedKey or null if invalid
 * 
 * @example
 * const key = fromStringWithDefault("my_item", myPlugin);
 * // Result: "myplugin:my_item" (uses plugin's namespace)
 */
export function fromStringWithDefault(key: string, defaultNamespace: any): BukkitNamespacedKey | null {
  return org.bukkit.NamespacedKey.fromString(key, defaultNamespace);
}